substitutions:
  _PATH_FROM_ROOT: 'apps/public-api' # This is needed since we are running the build in a monorepo.
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # - id: 'install'
  #   name: 'node'
  #   dir: '$_PATH_FROM_ROOT'
  #   entrypoint: 'npm'
  #   args: ['install']
  # - id: 'build'
  #   name: 'node'
  #   dir: '$_PATH_FROM_ROOT'
  #   entrypoint: 'npm'
  #   args: ['run', 'build']
  - id: 'isolate'
    name: 'node'
    dir: '$_PATH_FROM_ROOT'
    entrypoint: 'npx'
    args: ['isolate']
  - id: 'deploy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: '$_PATH_FROM_ROOT'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'public-api',
        # '--region',
        # '$_REGION',
        '--source',
        './isolate',
        '--set-env-vars',
        'APP_ENV=${_ENV}',
        # '--update-secrets',
        # 'SOME_SECRET=some-secret:latest'
      ]