dir: 'apps/public-api'
steps:
  - name: 'install'
    entrypoint: 'npm'
    args: ['ci']
  - name: 'build'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'isolate'
    entrypoint: 'npx'
    args: ['isolate']
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'public-api',
        '--source',
        './isolate',
        '--set-env-vars',
        'APP_ENV=${_ENV}',
        # '--update-secrets',
        # 'SOME_SECRET=some-secret:latest'
      ]